<a href="https://colab.research.google.com/github/zombie9088/Pytorch_learning/blob/main/dataset_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_classification
import torch


In [ ]:
X,y= make_classification(
    n_samples=10,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [ ]:
X

(10, 2)

In [ ]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [8]:
X= torch.tensor(X,dtype=torch.float32)
y= torch.tensor(y,dtype=torch.float32)

In [22]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [23]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [12]:
from torch.utils.data import Dataset,DataLoader

In [18]:
class CustomDataset(Dataset):

  def __init__(self, features,labels):
    self.features= features
    self.labels= labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]


In [19]:
dataset= CustomDataset(X,y)

In [20]:
len(dataset)    #can find length

10

In [24]:
dataset[0]      #can get any index

(tensor([ 1.0683, -0.9701]), tensor(1.))

In [25]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [26]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels )
  print("-"*50)

tensor([[-0.5872, -1.9717],
        [-1.9629, -0.9923]])
tensor([0., 0.])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.9382, -0.5430]])
tensor([0., 1.])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1., 0.])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [ 1.7273, -1.1858]])
tensor([1., 1.])
--------------------------------------------------
tensor([[ 1.7774,  1.5116],
        [-0.7206, -0.9606]])
tensor([1., 0.])
--------------------------------------------------
