<a href="https://colab.research.google.com/github/zombie9088/Pytorch_learning/blob/main/nn_module_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# import torch
# import torch.nn as nn

# #ineherit the nn.Module class

# class Model(nn.Module):

#   def __init__(self,num_features):

#     super().__init__()

#     self.linear1 = nn.Linear(num_features,3)
#     self.relu=nn.ReLU()
#     self.linear2=nn.Linear(3,1)
#     self.sigmoid=nn.Sigmoid()


#   def forward(self,features):
#     out= self.linear1(features)
#     out= self.relu(out)
#     out= self.linear2(out)
#     out= self.sigmoid(out)
#     return out

In [21]:
#rather than writing indiviadual layers we can wrap them in nn.Sequential

import torch
import torch.nn as nn

class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.network= nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
        )
  def forward(self,features):
    out = self.network(features)
    return out

In [22]:
features = torch.rand(10,5)

#create model
model=Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4260],
        [0.4502],
        [0.4263],
        [0.4317],
        [0.4296],
        [0.4169],
        [0.4408],
        [0.4459],
        [0.4374],
        [0.4590]], grad_fn=<SigmoidBackward0>)

In [28]:
model.network[0].weight

Parameter containing:
tensor([[ 0.3728, -0.3723,  0.0405, -0.2957,  0.3753],
        [-0.3586,  0.2123,  0.2319,  0.1967,  0.0534],
        [ 0.2308,  0.4146,  0.2701, -0.3158,  0.0377]], requires_grad=True)

In [25]:
model.network[0].bias

Parameter containing:
tensor([-0.3084,  0.2078,  0.4332], requires_grad=True)

In [29]:
model.network[2].weight

Parameter containing:
tensor([[ 0.1667,  0.5546, -0.1772]], requires_grad=True)

In [30]:
model.network[2].bias

Parameter containing:
tensor([-0.3100], requires_grad=True)

In [31]:
!pip install torchinfo
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00